### ISSUE TITLE
【エラー】bundle installすると、Could not locate Gemfileのエラーが出る

### ISSUE THREAD

**Issue by msm0046** [msm0046/chart_js_sample#4]
**エラーの理由**
ディレクトリを移動していなかったため？

**解決法**
ディレクトリを移動する
`$ cd chart_js_sample
`

`$ bundle install`を実行

<img width="630" alt="スクリーンショット 2020-07-17 5 50 23" src="https://user-images.githubusercontent.com/60738020/87721458-6a23d380-c7f1-11ea-851f-408a8e7f8db2.png">

**Comment by gouf** [comment]
これって `bundle install` を実行前に `bundle init` は実行されましたか?

**Comment by msm0046** [comment]
**原因**
`bundle init`忘れ！

**Comment by gouf** [comment]
解決した issue については close (≒ 終了) することができます！

**Comment by msm0046** [comment]
> 解決した issue については close (≒ 終了) することができます！

ありがとうございます！
